FROM mcr.microsoft.com/devcontainers/python:0-3.11


COPY ca_bundle.crt /usr/local/share/ca-certificates
RUN update-ca-certificates

COPY requirements.txt /tmp/pip-tmp/
RUN pip3 --proxy=http://web.prod.proxy.cargill.com:4300\
  --disable-pip-version-check \
  --trusted-host pypi.python.org \
  --no-cache-dir install -r /tmp/pip-tmp/requirements.txt \
  && rm -rf /tmp/pip-tmp

WORKDIR /app
COPY app/ ./

EXPOSE 8000
ENTRYPOINT [ "uvicorn", "--reload", "--host", "0.0.0.0", "fastapi_server:app" ]


```
 => [3/7] RUN update-ca-certificates                                                                                                                                                                             1.3s 
 => [4/7] COPY requirements.txt /tmp/pip-tmp/                                                                                                                                                                    0.0s 
 => ERROR [5/7] RUN pip3 --proxy=http://web.prod.proxy.cargill.com:4300  --disable-pip-version-check   --trusted-host pypi.python.org   --no-cache-dir install -r /tmp/pip-tmp/requirements.txt   && rm -rf /t  36.5s 
------
 > [5/7] RUN pip3 --proxy=http://web.prod.proxy.cargill.com:4300  --disable-pip-version-check   --trusted-host pypi.python.org   --no-cache-dir install -r /tmp/pip-tmp/requirements.txt   && rm -rf /tmp/pip-tmp:    
#0 9.525 WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)'))': /simple/llama-cpp-python/
#0 10.30 WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)'))': /simple/llama-cpp-python/
#0 11.63 WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)'))': /simple/llama-cpp-python/
#0 13.92 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)'))': /simple/llama-cpp-python/
#0 26.40 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)'))': /simple/llama-cpp-python/
#0 36.42 ERROR: Could not find a version that satisfies the requirement llama-cpp-python (from versions: none)
#0 36.43 ERROR: No matching distribution found for llama-cpp-python
------
failed to solve: executor failed running [/bin/sh -c pip3 --proxy=http://web.prod.proxy.cargill.com:4300  --disable-pip-version-check   --trusted-host pypi.python.org   --no-cache-dir install -r /tmp/pip-tmp/requirements.txt   && rm -rf /tmp/pip-tmp]: exit code: 1

 *  The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command docker compose -f "docker-compose.yml" up -d --build" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
 ```
